/** Configuração admin — sem elementos Route (evita o scanner Lovable). */
export const ADMIN_ROUTE_LOADERS = [
  { path: "/admin", module: () => import("@/views/admin/AdminDashboard.tsx") },
  { path: "/admin/plans", module: () => import("@/views/admin/AdminPlansPage.tsx") },
  { path: "/admin/routes", module: () => import("@/views/admin/AdminRoutesMapPage.tsx") },
  { path: "/admin/centrals", module: () => import("@/views/admin/AdminCentralsHubPage.tsx") },
  { path: "/admin/centrals/ai", module: () => import("@/views/admin/AdminCentralAiPage.tsx") },
  { path: "/admin/centrals/loyalty", module: () => import("@/views/admin/AdminCentralLoyaltyPage.tsx") },
  { path: "/admin/centrals/campaigns", module: () => import("@/views/admin/AdminCentralCampaignsPage.tsx") },
  { path: "/admin/centrals/push", module: () => import("@/views/admin/AdminCentralPushPage.tsx") },
  { path: "/admin/centrals/conversational", module: () => import("@/views/admin/AdminCentralConversationalPage.tsx") },
  { path: "/admin/monitoring", module: () => import("@/views/admin/MonitoringPage.tsx") },
  { path: "/admin/branding", module: () => import("@/views/admin/BrandingPage.tsx") },
  { path: "/admin/banner", module: () => import("@/views/admin/BannerPage.tsx") },
  { path: "/admin/operations", module: () => import("@/views/admin/OperationsPage.tsx") },
  { path: "/admin/printer", module: () => import("@/views/admin/PrinterPage.tsx") },
  { path: "/admin/users", module: () => import("@/views/admin/UsersPage.tsx") },
  { path: "/admin/settings", module: () => import("@/views/admin/SettingsPage.tsx") },
  { path: "/admin/guide", module: () => import("@/views/admin/GuidePage.tsx") },
  { path: "/admin/conversations", module: () => import("@/views/admin/AiConversationsPage.tsx") },
] as const;
