// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/** Storage local simples para evitar falha de plugin no arranque iOS. */
const nativeAuthStorage = {
  getItem: (key: string) => {
    if (typeof localStorage === "undefined") return null;
    try { return localStorage.getItem(key); } catch { return null; }
  },
  setItem: (key: string, value: string) => {
    if (typeof localStorage !== "undefined") {
      try { localStorage.setItem(key, value); } catch { /* noop */ }
    }
  },
  removeItem: (key: string) => {
    if (typeof localStorage !== "undefined") {
      try { localStorage.removeItem(key); } catch { /* noop */ }
    }
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: nativeAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: "kebabturco-auth",
  }
});

/** Hidrata sessão no arranque (não bloqueia se falhar). */
export async function hydrateAuthStorageBeforeBoot(): Promise<void> {
  return;
}
